name: Publish (latest)

on:
  release:
    types: [published]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: 16
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Version
        run: pnpm version --no-git-tag-version ${{ github.event.release.tag_name }}

      - name: Publish
        run: pnpm publish --access public --tag latest --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
